# Generated by Django 5.2.12 on 2026-09-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='jméno')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('message', models.TextField(verbose_name='zpráva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='odesláno')),
                ('is_read', models.BooleanField(default=False, verbose_name='přečteno')),
            ],
            options={
                'verbose_name': 'kontaktní zpráva',
                'verbose_name_plural': 'kontaktní zprávy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='název')),
                ('place', models.CharField(max_length=200, verbose_name='místo')),
                ('year', models.CharField(max_length=20, verbose_name='rok')),
                ('description', models.TextField(blank=True, verbose_name='popis')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='pořadí')),
            ],
            options={
                'verbose_name': 'výstava',
                'verbose_name_plural': 'výstavy',
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='název')),
                ('url', models.URLField(verbose_name='odkaz')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='popis')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='pořadí')),
            ],
            options={
                'verbose_name': 'odkaz',
                'verbose_name_plural': 'odkazy',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PressMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, verbose_name='zdroj')),
                ('text', models.TextField(verbose_name='text')),
                ('link', models.URLField(blank=True, verbose_name='odkaz')),
                ('date', models.DateField(blank=True, null=True, verbose_name='datum')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='pořadí')),
            ],
            options={
                'verbose_name': 'zmínka v tisku',
                'verbose_name_plural': 'napsali o něm',
                'ordering': ['-date', 'order'],
            },
        ),
    ]
