# Generated by Django 5.2.12 on 2026-09-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pressmention',
            options={'ordering': ['kind', 'order'], 'verbose_name': 'zmínka v tisku', 'verbose_name_plural': 'napsali o něm'},
        ),
        migrations.AddField(
            model_name='pressmention',
            name='kind',
            field=models.CharField(choices=[('quote', 'Citát'), ('publication', 'Publikace')], default='quote', max_length=20, verbose_name='druh'),
        ),
    ]
