# Generated by Django 5.2.12 on 2026-09-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pressmention_options_pressmention_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='description_en',
            field=models.TextField(blank=True, help_text='Nepovinné. Prázdné = zobrazí se český text.', verbose_name='popis (EN)'),
        ),
        migrations.AddField(
            model_name='pressmention',
            name='text_en',
            field=models.TextField(blank=True, help_text='Nepovinné. Citáty a bibliografie se nepřekládají strojově — prázdné pole znamená, že se zobrazí český originál.', verbose_name='text (EN)'),
        ),
    ]
