# Generated by Django 5.2.12 on 2026-09-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exhibition_description_en_pressmention_text_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallink',
            name='icon',
            field=models.CharField(choices=[('library', 'Knihovna / muzeum'), ('wiki', 'Encyklopedie'), ('catalog', 'Katalog / databáze děl'), ('gallery', 'Galerie'), ('generic', 'Neutrální (typ z názvu nevyplývá)')], default='generic', help_text='Typ odhadnutý z názvu odkazu. Když si nejste jistí, nechte neutrální — nic se tím netvrdí o obsahu odkazu.', max_length=20, verbose_name='ikona'),
        ),
    ]
