# Generated by Django 5.2.12 on 2026-09-08 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='název')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='pořadí')),
            ],
            options={
                'verbose_name': 'kategorie',
                'verbose_name_plural': 'kategorie',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='název')),
                ('year', models.CharField(blank=True, max_length=20, verbose_name='rok vzniku')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='rozměry')),
                ('technique', models.CharField(blank=True, max_length=150, verbose_name='technika')),
                ('image', models.ImageField(upload_to='paintings/%Y/%m/', verbose_name='obrázek')),
                ('image_alt', models.CharField(max_length=200, verbose_name='alt text obrázku')),
                ('description', models.TextField(blank=True, verbose_name='popis')),
                ('availability', models.CharField(choices=[('available', 'K dispozici'), ('sold', 'Prodáno'), ('not_for_sale', 'Neprodejné')], default='not_for_sale', max_length=20, verbose_name='dostupnost')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='pořadí zobrazení')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paintings', to='gallery.category', verbose_name='kategorie')),
            ],
            options={
                'verbose_name': 'obraz',
                'verbose_name_plural': 'obrazy',
                'ordering': ['order', '-year'],
            },
        ),
    ]
