# Generated by Django 5.2.12 on 2026-09-20 21:43

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Doplní slugy existujícím obrazům: <kategorie|název>-<kód>."""
    Painting = apps.get_model('gallery', 'Painting')
    for painting in Painting.objects.select_related('category'):
        base = slugify(painting.display_title) or slugify(painting.category.name)
        code = slugify(painting.title)
        painting.slug = f'{base}-{code}'.strip('-') if base else code
        painting.save(update_fields=['slug'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, help_text='Nepovinné. Prázdné = zobrazí se český název i v anglické verzi.', max_length=100, verbose_name='název (EN)'),
        ),
        migrations.AddField(
            model_name='painting',
            name='description_en',
            field=models.TextField(blank=True, help_text='Nepovinné. Prázdné = návštěvník uvidí český text s poznámkou.', verbose_name='popis (EN)'),
        ),
        migrations.AddField(
            model_name='painting',
            name='display_title',
            field=models.CharField(blank=True, help_text='Skutečný název díla, je-li znám. Prázdné = použije se „kategorie + kód“.', max_length=200, verbose_name='název obrazu'),
        ),
        # Slug se nejdřív přidá bez unique, naplní se u stávajících obrazů
        # a teprve pak se zamkne jako jedinečný.
        migrations.AddField(
            model_name='painting',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=220, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.RunPython(populate_slugs, noop),
        migrations.AlterField(
            model_name='painting',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='title',
            field=models.CharField(help_text='Kód z autorova katalogu, např. K1. Slouží i jako identifikátor při poptávce.', max_length=200, verbose_name='kód obrazu'),
        ),
    ]
